default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: lethunder1014
  username: deployer

development:
  <<: *default
  database: rapidfire_demo

production:
  <<: *default
  database: rapidfire_prod

